# Generated by Django 5.1.5 on 2025-01-29 13:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('post', 'user')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='ip_address',
        ),
    ]
